### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 38: invalid start byte

### ISSUE THREAD

**Issue by cquiroscrc** [m-jishnu/alt-app-installer#25]
Occurs at the end of the install

**Comment by m-jishnu** [comment]
can you share me the log.txt, it would be helpful if you also tell the name of the app you were trying to install and your system information (windows version, system arch)

**Comment by kejmlch** [comment]
I have a similar problem

log.txt:
[powershell logs] 
[02-02-2023 21:51:17]
command: Add-AppPackage "C:\Prog\alt app installer/downloads/5913DefineStudio.PhotoScan_4.0.4.0_x64__jj4r3mnwe2ey2_23c1aa22-c71a-4f9c-bd94-7b7d10f5f52d.msix"

[python logs] 
[02-02-2023 21:51:17]

Traceback (most recent call last):
  File "maingui.py", line 89, in run
  File "maingui.py", line 394, in <lambda>
  File "maingui.py", line 361, in install_thread
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 63: invalid continuation byte
----------------------------------------------------------------------------------


OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000
System Type:               x64-based PC
Alt App Installer v2.5.7

**Comment by m-jishnu** [comment]
@kejmlch thanks for the info! I have fixed the issue it was produced when the app was logging errors, the error was encoded in different format than the one i was decoding it with, can you check [v2.5.8](https://github.com/m-jishnu/alt-app-installer/releases/tag/v2.5.8) to confirm if its fixed or not

**Comment by m-jishnu** [comment]
closing this as it should be fixed in v2.5.9
