### ISSUE TITLE
#bug "Install from file" Option not responding and force the app stopped

### ISSUE THREAD

**Issue by acticu** [m-jishnu/alt-app-installer#29]
Hi,

I installed the app on Windows 10 (1909 and 21H2) using the offical installer.exe (version 2.6). When I clicked the install from file option, the whole window got unresponding and freezed immediately and I need to force close the app. Any solutions?

Kind regards,
Brian

**Comment by m-jishnu** [comment]
can you provide me with log.txt file

**Comment by acticu** [comment]
![image](https://user-images.githubusercontent.com/96876445/225200089-b1b6e770-88be-4452-80d6-6661b4502ae0.png)
The screenshot is like this and no log file was generated since this is the first time I run the application

**Comment by acticu** [comment]
I just simply clicked the option and it got frozen screen.

**Comment by m-jishnu** [comment]
can you tell me your system architecture, also can you try to build it from source and check if the issue still exist

**Comment by m-jishnu** [comment]
no reply provided
