### ISSUE TITLE
Virustotal detections?

### ISSUE THREAD

**Issue by the9655a** [m-jishnu/alt-app-installer#44]
Hi,

This app seems to trigger a lot of detections on virustotal. I did a re-scan, and its now at 35. Results: https://www.virustotal.com/gui/file/bd31a0e652093b8aff947803e3824962f58a5b31940479e1329da2646e8c25f2

Is there a reason why there are so many? And what is triggering it?

**Comment by m-jishnu** [comment]
to be frank i don't know either, i have always distributed the app like this in the past it didn't trigger anything but the current version unfortunately seem to trigger these anti malware scanners. the app doesn't perform any malicious activities you can check source code if you are still skeptical build from source and if possible vote/comment and say its not a virus in virus total or similar sites.

the executable is a pyinstaller file compressed using nanazip, my current hunch is that latest version of pyinstaller uses a new dir format now all app files are stored under _internal i think its go to do something with these false Positives

**Comment by the9655a** [comment]
Ah okay, thanks.
