### ISSUE TITLE
error code:  0x87E10BC6

### ISSUE THREAD

**Issue by javad7899** [m-jishnu/alt-app-installer#48]
whene i run app that installed from alt-app-installer, the app give me this error "Something happened on our end. Here’s the error code, in case you need it: 0x87E10BC6".

**Comment by m-jishnu** [comment]
hey, so the app that you installed crashes and gives this error, can you provide its name and your windows version like win 11 22h2 the 22h2 part is needed also provide your system architecture and tell if you are using custom iso like tiny10

**Comment by m-jishnu** [comment]
closing this as no reply provided, feel free to reopen after providing the relevant information.
