### ISSUE TITLE
Can't check the About!! 

### ISSUE THREAD

**Issue by uuc110** [m-jishnu/alt-app-installer#49]
I was checking the current version of my Alt app installer and clicked on about and it took me to the browser to the repo. and I guess this is the issue. it doesn't tell your the current version but repo, which won't lett you know what's the current version.  maybe user should know wheater the use is already uptodate or jsut way back old version. same with check version. it take me to release page. but won't tell user that is it already update or need a update.

**Comment by m-jishnu** [comment]
this is the intended behavior i didn't implement the about and check version it just redirect you to repo.i might implement it in future.

**Comment by m-jishnu** [comment]
added about section check [v2.6.8](https://github.com/m-jishnu/alt-app-installer/releases/tag/v2.6.8)

**Comment by uuc110** [comment]
> added about section check [v2.6.8](https://github.com/m-jishnu/alt-app-installer/releases/tag/v2.6.8)

Really Appriciate it to bring this immideatly after I reported it.💯 and yea its A Great tool🥹😇
